### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by vigkri** [scy-phy/minicps#1]
Hi. I recently installed Minicps in my PC but faced the following problem while doing a **plc1 ifconfig** :   

**File "plc1.py", line 12, in <module> disk = PLC1_DATA)
File "/usr/lib/python2.7/minicps/devices.py", line 74 in __init__self._init_state()
File "/usr/lib/python2.7/minicps/devices.py", line 152, in_init_state self._state = SQLITEState(self.state)
File "/usr/lib/python2.7/minicps/states.py", line 93, in __init__raise ValueError('Primary key not found')**
**ValueError: Primary Key not found.**

Please help.

**Comment by francozappa** [comment]
Hi @vigkri ,

Can you please tell me more detailed information about your settings and the error ?

Something like :

- I've installed MiniCPS on the official Mininet VM
- I run `make tests`
- Etc

From the error message, It looks like you have not initialized the database.

p.s. consider the following link to format your comments on GitHub
https://guides.github.com/features/mastering-markdown/

Thanks.

**Comment by vigkri** [comment]
Hi,

   -     I have installed Minicps inside the Mininet framework. I also have
   run the *make tests* command.
   -     For testing an example, I ran *make swat-s1*
   -     Inside the mininet console of swat-s1, I did an *ifconfig* for
   plc1 after which I got the above error.

   I am new to this environment. Kindly help.


   Thanking you,
   Vigkri

**Comment by francozappa** [comment]
Hi @vigkri 

> - Inside the mininet console of swat-s1, I did an *ifconfig* for

Once you run `make swat-s1` you should see a `mininet> ` prompt. Then if you want to run `ifconfig` 
on the `plc1` host you should run `xterm plc1` and get an xterm window (notice that if you are using ssh to connect to the vm please use the `-Y` option to enable (safe) X11 forwarding. Then from the new xterm window type `ifconfig`. An laternative way is to run `plc1 ifconfig` directly on the `mininet> ` prompt.

Let me know your progresses :+1:

**Comment by vigkri** [comment]
It is working now. Thanks for the help. But I'm still unable to run plc1.py (**python plc1.py**) from plc1's xterm window. It gives me the above error.

**Comment by francozappa** [comment]
If you look at the doc:
http://minicps.readthedocs.io/en/latest/swat-tutorial.html#customization

You will see that by default the simulated PLCs and the physical process simulation are not automatically started. If you uncomment the `*.cmd(...)` lines, you will automatically start the devices and the physical process  each time you `make swat-s1`.

Let me know if I can close the issue.

**Comment by vigkri** [comment]
OK thanks for the help.
