### ISSUE TITLE
swat-s1 Tutorial

### ISSUE THREAD

**Issue by dkalog** [scy-phy/minicps#15]
Hi  *
Congrats for your amazing effort in the CPS simulation. I am trying to replicate the case described in swat-tutorial.rst.  So I run  make swat-s1-init . Then I run make swat-s1. (This executed the run.py .. tested the ping between the attacker and plc1,plc2 and plc3 and ended in the mininet prompt.. from which I exited with quit() ). 

I expect after a simulation run at every time-tick there should be a cyber and physical log entry output-ed in a directory or a database ?  Where is this stored ?

Cheers,
Dimitris

PS. The logs subdir in the swat-s1 contains some 0 size files and an protocols_enip_tests_server. There is also a dir real-tags which does not collect any logs. (are those dirs of any usage ?)

**Comment by francozappa** [comment]
Hi @dkalog,

> Congrats for your amazing effort in the CPS simulation

Thanks 👍 

> I expect after a simulation run at every time-tick there should be a cyber and physical log entry output- ed in a directory or a database ? Where is this stored ?

The `swat-s1` simulation is just a basic example, however you can customize the code to log specific cyber and physical data that are exchanged at runtime and use the `logs` folder to store your log files.

Please let me know if you need more help!
