### ISSUE TITLE
Travis: pymodbus tests failing

### ISSUE THREAD

**Issue by francozappa** [scy-phy/minicps#17]
`pymodbus` is giving some trouble on the Travis server and consequently some tests are failing remotely but not locally.

**Comment by pgaulon** [comment]
Hello,

The errors showed in https://travis-ci.org/scy-phy/minicps are:
$ pip install -r requirements.txt
[...]
    from twisted.internet import protocol
ImportError: No module named twisted.internet

So I think the fix is as simple as adding the module twisted to requirements.txt.

**Comment by francozappa** [comment]
Closed by #21
