### ISSUE TITLE
Empty ENIP-Tags

### ISSUE THREAD

**Issue by lenaglas** [scy-phy/minicps#28]
I keep facing a problem while running the example project swat-s1. Whilst init.py works and I can start run.py seeing the `mininet>` prompt the PLCs are not communication correctly as the ENIP-Tags are not filled properly. When I start plc1.py (after having started plc2 and plc3) i get the error:
```
fit201 = float(self.receive(FIT201_2, PLC2_ADDR))
ValueError: could not convert string to float:
```
Debugging showed me that this is because fit201 is just an empty string.
Could you maybe help me what I'm missing out here?

**Comment by lenaglas** [comment]
It seems that a new version of cpppo (4.4) caused the error, everything works fine again with version 4.3.4 so` pip uninstall cpppo` and `pip install cpppo=4.3.4` solved my problem.

**Comment by Gargi-Mitra** [comment]
I was also getting the same error. Uninstalling cpppo 4.4 and installing cpppo version 4.3.4 has not solved it. I am still getting the error.
