### ISSUE TITLE
Sending UDP data to controller

### ISSUE THREAD

**Issue by tilaprimera** [scy-phy/minicps#7]
Can PLC's send udp packets to the controller?

**Comment by francozappa** [comment]
Hi @tilaprimera,

When you say controller you mean the SDN controller?

What type of UDP traffic do you want to send?

**Comment by tilaprimera** [comment]
Thank you.

Yes, I meant the SDN controller.

I am trying to send a UDP packet with information such as:

1. YES/No
2. Source hostname
3. Destination hostname
4. Probability

Thank you so much for your response.

**Comment by francozappa** [comment]
Why aren't you using Openflow (over TCP) to communicate with the SDN controller?

I have to close this issue because it is not directly related with MiniCPS.

**Comment by tilaprimera** [comment]
Thank you.
